### PR TITLE
Fixed index issue, and ivkey not being parsed correctly.

### PR DESCRIPTION
**Pull request by Valentinez**
Fixed it up to parse key and decrypt ivkey correctly.

### CODE REVIEW

**Comment by shinvou** [comment]
I don't even know what you are trying to do. Do you want to explain these changes?

**Comment by Valentinez** [comment]
Kept getting Index Error on this line:
`ivkey = str(subprocess.run([ipwndfu_path + 'ipwndfu', '--decrypt-gid', keybag], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.strip(), 'utf-8').split('\n')[1]`

Since, at least to my belief, you need Key=Keybag line 1
and ivkey=[Decrypted]Keybag line 2, 

This line:
`keybag = str(subprocess.run(['img4', '-i', file, '-b'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.strip(), 'utf-8').split('\n')[0]`

Was only returning Keybag line 1, 
Because str.split('/n')[0] only grabs line 1
So resulting Keybag only had 1 key.

Need to grab both lines, so:

```
keybag = str(subprocess.run(['img4', '-i', file, '-b'], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout, 'utf-8') #splitlines come later, do not need to strip()
...
        key  = keybag.splitlines()[0] 
        key2 = keybag.splitlines()[1]
```
Now we have both lines.

Also,
`[ipwndfu_path + 'ipwndfu', '--decrypt-gid', keybag] `
needs to be
`[ipwndfu_path + 'ipwndfu', '--decrypt-gid=' + keybag]`

As ipwndfu -h states command as `--decrypt-gid=hexdata`

Another thing was, the first line after running `ipwndfu --decrypt-gid=keybag`
is actually: `Decrypting with %s GID key.`

No ability to grab second output, which is ivkey we need.
Tried to .splitlines()[1], however
Kept getting that index error, 
Tried to print out all lines for ivkey, only returned first output...
Which is `Decrypting with %s GID key.`
so, need to edit ipwndfu file to stop that extra output:

```
ipwndfu around line 318:
--------------------------------------------------
        if opt == '--decrypt-gid':
           device = dfu.acquire_device()
           serial_number = device.serial_number
           dfu.release_device(device)

           if 'PWND:[checkm8]' in serial_number:
               pwned = usbexec.PwnedUSBDevice()
 Comment out>>> #print 'Decrypting with %s GID key.' % pwned.platform.name()
               print pwned.aes(arg.decode('hex'), usbexec.AES_DECRYPT,  usbexec.AES_GID_KEY).encode('hex') 
--------------------------------------------------
```
Also needed ivkey=str().strip(), as it seemed to come with two returns
when running the code without it.

Now it successfully outputs decrypted ivkey. [For me, anyhow]
Not sure if decrypted files are really decrypted,
as I'm not sure what program to read them with,
So I can test.

I'm using Ubuntu 18.04 LTS, Python 3.6.8
and this version of ipwndfu: [Cryptiiiic/ipwndfu_public](https://github.com/Cryptiiiic/ipwndfu_public)

iPad Mini 3 [A1600] CPID: 8960

**Comment by shinvou** [comment]
Well, ok.

First of all:

> Also,
[ipwndfu_path + 'ipwndfu', '--decrypt-gid', keybag] 
needs to be
[ipwndfu_path + 'ipwndfu', '--decrypt-gid=' + keybag]

No it does not need to. Both works.

Second:

> Not sure if decrypted files are really decrypted,
as I'm not sure what program to read them with,
So I can test.

They are probably not. You need to pass key not key2 to ipwndfu. You could easily see if it worked when you pass the decrypted file to a hex editor and can read iBoot in the data. Also I don't really understand why you use this tool when you don't understand how to see if encryption worked or what to do with the files.

Last one:
I don't know why you get these errors. It's propably related to Ubuntu (or your img4), I use macOS. Our versions don't differ that much, I'm just splitting the keybags when I receive them and you do that later on. If you want my help: Please run the original version and paste the whole output here.

**Comment by Valentinez** [comment]
Ok, so there was my first misunderstanding, 
Thought that second line of Keybag to be decrypted to get ivkey.

The other, well, I knew I would probably need a Hex Editor, just wasn't sure if maybe there was some other type of program to read them, cause I know how picky Apple is.

New to this whole thing, more of a hobby for me anyhow.
I just like messing with electronics, and now I can mess with Apple Devices? 
Count me in~! Just taking things one step at a time.

First step was getting ipwndfu to work with device, had to tinker with that code, 
[from a fork of a fork]
now I can get it like 9/10 times.

I do honestly apologize for my misunderstanding, and creating a pull that isn't needed.
I just didn't want to post an issue about an index error, thought I could solve that myself.

Here's my Error, only changed path to ipwndfu in original file:
```
:~/Documents/decrypt0r-master$ python3 decrypt0r.py -fw 12.4.2
[*] Found iPad4,8 in DFU mode
[*] There are 61 firmwares available for iPad4,8
[*] Processing iOS 12.4.2 (only)
   [*] Found 37 files to download
   [*] Downloading Firmware/all_flash/DeviceTree.j82ap.im4p [1/37]
   [*] Decrypting Firmware/all_flash/DeviceTree.j82ap.im4p
      [*] We don't need to decrypt DeviceTree.j82ap.im4p
      [*] Moved to unencrypted/DeviceTree.j82ap.im4p
   [*] Downloading Firmware/all_flash/batterylow0@2x~ipad.im4p [2/37]
   [*] Decrypting Firmware/all_flash/batterylow0@2x~ipad.im4p
      [*] We don't need to decrypt batterylow0@2x~ipad.im4p
      [*] Moved to unencrypted/batterylow0@2x~ipad.im4p
   [*] Downloading Firmware/all_flash/LLB.ipad5b.RELEASE.im4p [3/37]
   [*] Decrypting Firmware/all_flash/LLB.ipad5b.RELEASE.im4p
      [*] Got keybag: 853E052CAA024F696F8F1608E5F2A398383A36E928DD9BFC563E894668FDCAD026B90A499CB93D20523BD1DCE2434588
Traceback (most recent call last):
  File "decrypt0r.py", line 134, in <module>
    process_firmware(firmware)
  File "decrypt0r.py", line 116, in process_firmware
    decrypt_file(real_filename)
  File "decrypt0r.py", line 73, in decrypt_file
    ivkey = str(subprocess.run([ipwndfu_path + 'ipwndfu', '--decrypt-gid', keybag], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL).stdout.strip(), 'utf-8').split('\n')[1]
IndexError: list index out of range
```
So it wasn't grabbing 2nd output at all, 
Even before my ipwndfu was edited, same error,
Even when I changed index to [0]
Which lead me on my edit.

However, now that my ipwndfu is edited,
[comment out the print statement to prevent extra output]

Changed index to that line to [0]...

Program works...
```
~/Documents/decrypt0r-master$ python3 decrypt0r.py -fw 12.4.2
[*] Found iPad4,8 in DFU mode
[*] There are 61 firmwares available for iPad4,8
[*] Processing iOS 12.4.2 (only)
   [*] Found 37 files to download
   [*] Downloading Firmware/all_flash/DeviceTree.j82ap.im4p [1/37]
   [*] Decrypting Firmware/all_flash/DeviceTree.j82ap.im4p
      [*] We don't need to decrypt DeviceTree.j82ap.im4p
      [*] Moved to unencrypted/DeviceTree.j82ap.im4p
   [*] Downloading Firmware/all_flash/batterylow0@2x~ipad.im4p [2/37]
   [*] Decrypting Firmware/all_flash/batterylow0@2x~ipad.im4p
      [*] We don't need to decrypt batterylow0@2x~ipad.im4p
      [*] Moved to unencrypted/batterylow0@2x~ipad.im4p
   [*] Downloading Firmware/all_flash/LLB.ipad5b.RELEASE.im4p [3/37]
   [*] Decrypting Firmware/all_flash/LLB.ipad5b.RELEASE.im4p
      [*] Got keybag: 853E052CAA024F696F8F1608E5F2A398383A36E928DD9BFC563E894668FDCAD026B90A499CB93D20523BD1DCE2434588
      [*] Got ivkey: 46f4a6cb4e1ad01bd3017b5bba89dfd404fa0c82417467c174a01f2e2701fad95e396768b1601e4f3e2caacb39a5224b
      [*] Decrypted file saved to decrypted/LLB.ipad5b.RELEASE.decrypted
   [*] Downloading Firmware/all_flash/batterycharging1@2x~ipad.im4p [4/37]
```

All because I thought I needed the 2nd key to be decrypted.
Made it more complicated than it need to be. 
Thank you for your time.

Will close request.

**Pull request closed without merging**
